search:src/searchInFile.py
	python3 src/searchInFile.py

regex:src/regex.py
	python3 src/regex.py

test:src/test.py
	python3 src/test.py

network:src/network/socket1.py
	python3 src/network/socket1.py

scrape:src/network/scrape.py
	python3 src/network/scrape.py

exercise:src/web-services/exercise-json-api.py
	python3 src/web-services/exercise-json-api.py

web:src/web-services/json2.py
	python3 src/web-services/json2.py

oops:src/oop/inheritance.py
	python3 src/oop/inheritance.py