# Algorithms
# 	A set of rules or steps used to solve a problem
# Data Structures:
#	A paticular way of organizing data in a computer

search:src/searchInFile.py
	python3 src/searchInFile.py

regex:src/regex.py
	python3 src/regex.py

test:src/test.py
	python3 src/test.py

network:src/network/socket1.py
	python3 src/network/socket1.py

scrape:src/network/scrape.py
	python3 src/network/scrape.py

exercise:src/network/bsExercise2.py
	python3 src/network/bsExercise2.py